import test from 'node:test';
import assert from 'node:assert/strict';
import { emptyProperties, numberValue, colorValue, unavailable } from '../packages/core/src/index';
import { structureScale, roundedShape, contentSize, rgba } from '../packages/ui/visual-model';
function box(){const p=emptyProperties();for(const key of ['width','height','paddingTop','paddingRight','paddingBottom','paddingLeft','borderTopWidth','borderRightWidth','borderBottomWidth','borderLeftWidth','radiusTopLeft','radiusTopRight','radiusBottomRight','radiusBottomLeft'] as const)p[key]=numberValue(0);p.width=numberValue(124);p.height=numberValue(100);return p;}
const css={'box-sizing':'content-box','overflow-x':'visible','overflow-y':'visible','scrollbar-gutter':'auto'};
test('visual common scale preserves reported +138 dimensions and asymmetrical values without mutating data',()=>{const a=box(),b=box();a.width=numberValue(282);a.height=numberValue(450.5);b.width=numberValue(420);b.height=numberValue(588.5);a.paddingLeft=numberValue(13);a.paddingRight=numberValue(21);const before=JSON.stringify([a,b]);const scale=structureScale([a,b]);assert.equal(scale,90/588.5);assert.ok((420-282)*scale>0);assert.ok((588.5-450.5)*scale>0);assert.equal(JSON.stringify([a,b]),before);});
test('web content derived only from known geometry/padding/border with no potential scrollbar; Figma never guessed',()=>{const p=box();p.paddingLeft=p.paddingRight=numberValue(10);p.borderLeftWidth=p.borderRightWidth=numberValue(2);assert.deepEqual(contentSize(p,'web',css).width,numberValue(100,'px','확인된 border-box − padding − border'));assert.equal(contentSize(p,'figma').width.status,'unknown');for(const overrides of [{'overflow-y':'auto'},{'overflow-x':'scroll'},{'scrollbar-gutter':'stable'},{'box-sizing':'unknown'}])assert.equal(contentSize(p,'web',{...css,...overrides}).width.status,'unknown');});
test('unknown and unsupported padding/border/transform dimensions stay N/A; negative content is never clamped',()=>{const p=box();p.paddingRight=unavailable('mixed');assert.equal(contentSize(p,'web',css).width.status,'unknown');p.paddingRight=numberValue(200);const result=contentSize(p,'web',css);assert.equal(result.width.status,'unknown');assert.match(result.width.reason,/음수/);p.width=unavailable('transform');assert.equal(contentSize(p,'web',css).width.status,'unknown');});
test('genuine zero content and radius are supported; asymmetric four corners remain exact and overlaps are not clamped',()=>{const p=box();p.width=p.height=numberValue(0);assert.equal(contentSize(p,'web',css).width.status,'supported');assert.deepEqual(roundedShape(p).radii,[0,0,0,0]);p.width=numberValue(124);p.height=numberValue(100);p.radiusTopLeft=numberValue(3);p.radiusTopRight=numberValue(9);p.radiusBottomRight=numberValue(17);p.radiusBottomLeft=numberValue(5);assert.deepEqual(roundedShape(p).radii,[3,9,17,5]);p.radiusTopLeft=numberValue(200);assert.equal(roundedShape(p).radii,undefined);p.radiusTopLeft=unavailable('corner smoothing');assert.equal(roundedShape(p).radii,undefined);});
test('visual RGBA preserves alpha zero and fractional channels; unsupported gradient and malformed colors never become paint',()=>{const value=colorValue([11.25,20.5,33,0]);const before=JSON.stringify(value);assert.deepEqual(rgba(value),[11.25,20.5,33,0]);assert.equal(JSON.stringify(value),before);assert.equal(rgba(unavailable('gradient/P3')),undefined);assert.equal(rgba({status:'supported',kind:'rgba',value:[256,0,0,1]}),undefined);});
